name: PDD Project CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=src
    
    - name: Lint with ruff
      run: |
        pip install ruff
        ruff check .
    
    - name: Format check with black
      run: |
        pip install black
        black --check .

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security checks
      uses: securecodewarrior/github-action-add-sarif@v1
      with:
        sarif-file: 'security-results.sarif'

  phr-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate PHR format
      run: |
        python -c "
        import os
        import re
        from pathlib import Path
        
        phr_dir = Path('docs/prompts')
        if phr_dir.exists():
            for phr_file in phr_dir.glob('*.prompt.md'):
                content = phr_file.read_text()
                if not re.search(r'^---\s*id:\s*\d+', content, re.MULTILINE):
                    print(f'Invalid PHR format: {phr_file}')
                    exit(1)
            print('All PHRs are valid')
        else:
            print('No PHRs to validate')
        "
